ALTER SESSION SET NLS_NUMERIC_CHARACTERS=',.';
REM Nombre : LISTADO1.SQL
REM Descripción: Listado de Empleados.
TTITLE 'LISTADO DE LOS EMPLEADOS DE LA TABLA EMPLE' skip 2
BTITLE 'Con ruptura por departamento y por oficio calculando totales' skip 2
SET HEADSEP |

COLUMN LOC HEADING 'Localidad' 
COLUMN APELLIDO HEADING 'Apellido'
COLUMN EMPLE_NO HEADING 'Número de| empleado' 
COLUMN OFICIO HEADING 'Oficio' FORMAT A10
COLUMN SALARIO HEADING 'Salario' FORMAT 9G999G999
COLUMN COMISION HEADING 'Comisión' FORMAT 9G999G999


BREAK ON LOC SKIP 2 ON OFICIO SKIP 1

COMPUTE SUM LABEL'Suma por loc.' OF SALARIO ON LOC 
COMPUTE SUM LABEL'Sum por ofi.' OF SALARIO ON oficio 

SET LINESIZE 79
SET PAGESIZE 70
SET NEWPAGE 0

SPOOL D:\ej\LISTADO1.LST

SELECT LOC, APELLIDO, EMPLE_NO, OFICIO, SALARIO, COMISION
FROM EMPLE, DEPART
WHERE EMPLE.DEPART_NO=DEPART.DEPART_NO
ORDER BY LOC, OFICIO;

SPOOL OFF
TTITLE OFF
BTITLE OFF
CLEAR BREAKS
CLEAR COMPUTES
CLEAR COLUMNS

