productos:
  - nombre: "Producto 1"
    precio: 100
    descripcion: "Descripcion del producto 1"
  - nombre: "Producto 2"
    precio: 200
    descripcion: "Descripcion del producto 2"
  - nombre: "Producto 3"
    precio: 300
    descripcion: "Descripcion del producto 3"