REM Nombre : LISTADO4.SQL
REM Descripción: Listado de SALARIOS - INTRODUCIMOS DEPARTAMENTO
SET HEADSEP |
SET UNDERLINE -

TTITLE CENTER 'LISTADO DE LOS SALARIOS DE LOS EMPLEADOS' skip 2
COLUMN DNOMBRE HEADING 'Nombre|Departamento'
COLUMN SALARIO FORMAT 9G999G999

BREAK ON DNOMBRE SKIP 1
COMPUTE SUM MAX MIN AVG OF SALARIO ON DNOMBRE

SET LINESIZE 79
SET PAGESIZE 30 
SET NEWPAGE 0

SPOOL d:\ej\LISTADO4.LST
ACCEPT NOM PROMPT "Nombre de departamento a listar:";

SELECT DNOMBRE, APELLIDO, SALARIO 
FROM EMPLE, DEPART
WHERE EMPLE.DEPART_NO=DEPART.DEPART_NO AND LOWER(DNOMBRE) LIKE LOWER('%&NOM%')
ORDER BY DNOMBRE;


TTITLE OFF
BTITLE OFF
CLEAR BREAKS
CLEAR COMPUTES
CLEAR COLUMNS
SPOOL OFF
