REM Nombre : LISTADO2.SQL
REM Descripción: RESUMEN POR DEPARTAMENTOS

SET HEADSEP |

TTITLE CENTER 'RESUMEN POR DEPARTAMENTOS' skip 2

COLUMN DNOMBRE HEADING 'Nombre|Departamento'
COLUMN MAXIMO HEADING 'Maximo|Salario' FORMAT 9G999
COLUMN MINIMO HEADING 'Minimo|Salario' FORMAT 9G999
COLUMN SUMA HEADING 'Suma|Salarios' FORMAT 9G999G999
COLUMN MEDIO HEADING 'Salario|Medio' FORMAT 9G990D00
COLUMN CUENTA HEADING 'Numero|Empleados' FORMAT 9G999

SET LINESIZE 80
SET PAGESIZE 60 
SET NEWPAGE 0

SPOOL d:\LISTADO2.LST

SELECT DNOMBRE, nvl(max(salario),0) MAXIMO, nvl(min(salario),0) MINIMO, 
        nvl(sum(salario),0) SUMA, nvl(avg(salario),0) MEDIO, nvl(count(apellido),0) CUENTA
FROM EMPLE, DEPART
WHERE EMPLE.DEPART_NO (+)=DEPART.DEPART_NO
GROUP BY DNOMBRE;

SPOOL OFF

TTITLE OFF
BTITLE OFF
CLEAR COLUMNS
